/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package leave.application;

import java.io.File;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JTextField;
import static leave.application.Submit.att;
import static leave.application.Submit.ed;
import static leave.application.Submit.hide1;
import static leave.application.Submit.jLabel5;
import static leave.application.Submit.rea1;
import static leave.application.Submit.reasonla1;

/**
 *
 * @author Dhanya Sudhakaran
 */
public class leave extends javax.swing.JFrame {
    /**
     * Creates new form leave
     */
    public leave() {
        initComponents();
        sub.setVisible(false);
        stdatela.setVisible(false);
        startdate.setVisible(false);
        enddate.setVisible(false);
        eddatela.setVisible(false);
        labeledate.setVisible(false);
        labele_emr.setVisible(false);
        labelannual1.setVisible(false);
        reason.setVisible(false);
        reasonla.setVisible(false);
        scrolreason.setVisible(false);
        upload.setVisible(false);
        jTextField1.setVisible(false);
        jButton1.setVisible(false);
        labelmed.setVisible(false); 
        
        String reason1 = reason.getText();
        String upload1 = jTextField1.getText();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        startdate = new com.toedter.calendar.JDateChooser();
        stdatela = new javax.swing.JLabel();
        eddatela = new javax.swing.JLabel();
        enddate = new com.toedter.calendar.JDateChooser();
        reasonla = new javax.swing.JLabel();
        labeledate = new javax.swing.JLabel();
        labelmed = new javax.swing.JLabel();
        scrolreason = new javax.swing.JScrollPane();
        reason = new javax.swing.JTextArea();
        sub = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        upload = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        labele_emr = new javax.swing.JLabel();
        labelannual1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(549, 409));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 689));
        jPanel1.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dhanya Sudhakaran\\Downloads\\background.jpg")); // NOI18N
        jLabel7.setText("E");
        jLabel7.setOpaque(true);
        jLabel7.setRequestFocusEnabled(false);
        jLabel7.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 0, 570, 70);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Medical Leave", "Emergency Leave", "Annual Leave" }));
        jComboBox1.setSelectedItem(null);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(190, 110, 200, 30);

        jLabel1.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        jLabel1.setText("Type of leave");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 110, 120, 30);
        jPanel1.add(startdate);
        startdate.setBounds(120, 180, 140, 20);

        stdatela.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        stdatela.setText("Start Date");
        jPanel1.add(stdatela);
        stdatela.setBounds(30, 180, 80, 21);

        eddatela.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        eddatela.setText("End Date");
        jPanel1.add(eddatela);
        eddatela.setBounds(30, 240, 80, 21);
        jPanel1.add(enddate);
        enddate.setBounds(120, 240, 140, 20);

        reasonla.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        reasonla.setText("Reason");
        jPanel1.add(reasonla);
        reasonla.setBounds(310, 180, 70, 21);

        labeledate.setFont(new java.awt.Font("Footlight MT Light", 2, 14)); // NOI18N
        labeledate.setForeground(new java.awt.Color(255, 0, 0));
        labeledate.setText("*Date field is empty");
        jPanel1.add(labeledate);
        labeledate.setBounds(30, 210, 260, 20);

        labelmed.setFont(new java.awt.Font("Footlight MT Light", 2, 14)); // NOI18N
        labelmed.setForeground(new java.awt.Color(255, 0, 0));
        labelmed.setText("*Medical Report should be uploaded");
        jPanel1.add(labelmed);
        labelmed.setBounds(140, 300, 340, 14);

        reason.setColumns(20);
        reason.setRows(5);
        scrolreason.setViewportView(reason);

        jPanel1.add(scrolreason);
        scrolreason.setBounds(370, 180, 166, 96);

        sub.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        sub.setText("SUBMIT");
        sub.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActionPerformed(evt);
            }
        });
        jPanel1.add(sub);
        sub.setBounds(220, 350, 60, 30);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText(".....");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(380, 320, 40, 20);

        upload.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        upload.setText("Upload Medical Report");
        jPanel1.add(upload);
        upload.setBounds(70, 320, 150, 20);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Bell MT", 2, 12)); // NOI18N
        jLabel2.setText("LOG OUT");
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(490, 70, 60, 20);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(240, 320, 180, 20);

        labele_emr.setFont(new java.awt.Font("Footlight MT Light", 2, 14)); // NOI18N
        labele_emr.setForeground(new java.awt.Color(255, 0, 0));
        labele_emr.setText("*This is for a day");
        jPanel1.add(labele_emr);
        labele_emr.setBounds(20, 270, 260, 20);

        labelannual1.setFont(new java.awt.Font("Footlight MT Light", 2, 14)); // NOI18N
        labelannual1.setForeground(new java.awt.Color(255, 0, 0));
        labelannual1.setText("*Application to be submitted 10 days before the start date");
        jPanel1.add(labelannual1);
        labelannual1.setBounds(20, 300, 340, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //jComboBox1.addActionListener(new ActionListener();
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
       // JComboBox jComboBox1= (JComboBox)event.getSource();
        Object selected = jComboBox1.getSelectedItem();
        LocalDate startannual =  LocalDate.now().plusDays(10);
        LocalDate endannual =  startannual.plusDays(30);
        Date stan;
        Date endan;
        
        stan = Date.from(startannual.atStartOfDay().atZone(ZoneId.systemDefault()).toInstant());
        endan = Date.from(endannual.atStartOfDay().atZone(ZoneId.systemDefault()).toInstant());
        
        if(selected.toString() == null) {
            sub.setVisible(false);
            stdatela.setVisible(false);
            startdate.setVisible(false);
            enddate.setVisible(false);
            eddatela.setVisible(false);
            labeledate.setVisible(false);
            labelmed.setVisible(false);
            labelannual1.setVisible(false);
            reason.setVisible(false);
            reasonla.setVisible(false);
            scrolreason.setVisible(false);
            jTextField1.setVisible(false);
            jButton1.setVisible(false);
           
        } else
        {
            switch (selected.toString()) {
                case "Emergency Leave":
                    sub.setVisible(true);
                    stdatela.setVisible(true);
                    startdate.getJCalendar().setMinSelectableDate(new Date());
                    startdate.setVisible(true);
                    enddate.setVisible(false);
                    eddatela.setVisible(false);
                    labelannual1.setVisible(false);
                    labele_emr.setVisible(true);
                    labelmed.setVisible(false);
                    reason.setVisible(false);
                    reasonla.setVisible(false);
                    scrolreason.setVisible(false);
                    upload.setVisible(false);
                    jTextField1.setVisible(false);
                    jButton1.setVisible(false);
                    break;
                case "Annual Leave":
                    sub.setVisible(true);
                    stdatela.setVisible(true);
                    startdate.getJCalendar().setMinSelectableDate(stan);
                    startdate.setVisible(true);
                    enddate.getJCalendar().setMinSelectableDate(endan);
                    enddate.setVisible(true);
                    eddatela.setVisible(true);
                    labeledate.setVisible(false);
                    labele_emr.setVisible(false);
                    labelannual1.setVisible(true);
                    reason.setVisible(false);
                    reasonla.setVisible(false);
                    scrolreason.setVisible(false);
                    upload.setVisible(false);
                    jTextField1.setVisible(false);
                   jButton1.setVisible(false);
                    break;
                default:
                    sub.setVisible(true);
                    stdatela.setVisible(true);
                    startdate.getJCalendar().setMinSelectableDate(new Date());
                    startdate.setVisible(true);
                    enddate.getJCalendar().setMinSelectableDate(new Date());
                    enddate.setVisible(true);
                    eddatela.setVisible(true);
                    labeledate.setVisible(false);
                    labele_emr.setVisible(false);
                    labelannual1.setVisible(false);
                    reason.setVisible(true);
                    reasonla.setVisible(true);
                    scrolreason.setVisible(true);
                    upload.setVisible(true);
                    jTextField1.setVisible(true);
                    jButton1.setVisible(true);
                    break;
            }
                
            
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed
/**/
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.hide();
        new loginPage().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          JFileChooser ch = new JFileChooser();
        ch.showOpenDialog(null);
        File f = ch.getSelectedFile();
        String filname = f.getAbsolutePath();
        jTextField1.setText(filname);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActionPerformed
       
        Object selected = jComboBox1.getSelectedItem();
        String enddate2 = enddate.getDate().toString();
        String startdate2= startdate.getDate().toString();
        
        switch (selected.toString()) {
                case "Emergency Leave":if(!startdate2.equals(""))
                {
                    new Submit().setVisible(true);
                    this.hide();
                    Submit.id.setText(loginPage.username.getText());
                    Submit.leave.setText((String) selected);
                    Submit.dat.setText(startdate2);
                    //Submit.ed.setText(enddate1);
                    //Submit.rea1.setText(reason.getText());
                    //Submit.att.setText(jTextField1.getText());
                    hide1.setVisible(false);
                    ed.setVisible(false);
                    reasonla1.setVisible(false);
                    rea1.setVisible(false);
                    jLabel5.setVisible(false);
                    att.setVisible(false);
                }
               else
                {
                    labeledate.setVisible(true);
                }
                 break;
                case "Annual Leave":if(!startdate2.equals("")&&!enddate2.equals("")) 
                {
                    new Submit().setVisible(true);
                    this.hide();
                    Submit.id.setText(loginPage.username.getText());
                    Submit.leave.setText((String) selected);
                    Submit.dat.setText(startdate2);
                    Submit.ed.setText(enddate2);
                    //Submit.rea1.setText(reason.getText());
                    // Submit.att.setText(jTextField1.getText());
                    hide1.setVisible(true);
                    ed.setVisible(true);
                    reasonla1.setVisible(false);
                    rea1.setVisible(false);
                    jLabel5.setVisible(false);
                    att.setVisible(false);
                }
                else {
                    labeledate.setVisible(true);
                    startdate.setDate(null);
                    enddate.setDate(null);
                    }
                       break;
                default: if(startdate2.equals("")||enddate2.equals("")) 
                            {
                               labeledate.setVisible(true); 
                            }
                        else if (jTextField1.getText().equals(""))
                         {
                         labelmed.setVisible(true); 
                         }
                        else {
                             new Submit().setVisible(true);
                             this.hide();
                             Submit.id.setText(loginPage.username.getText());
                             Submit.leave.setText((String) selected);
                             Submit.dat.setText(startdate2);
                             Submit.ed.setText(enddate2);
                             Submit.rea1.setText(reason.getText());
                             Submit.att.setText(jTextField1.getText());
                             hide1.setVisible(true);
                             ed.setVisible(true);
                             reasonla1.setVisible(true);
                             rea1.setVisible(true);
                             jLabel5.setVisible(true);
                             att.setVisible(true);
                             }
                        break;
        }            
    }//GEN-LAST:event_subActionPerformed
    /*public void setMinSelectableDate(java.LocalDate.now())
    {
     startdate.setMinSelectableDate(newd);  
    }*/
    /**/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(leave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(leave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(leave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(leave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new leave().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eddatela;
    private com.toedter.calendar.JDateChooser enddate;
    private javax.swing.JButton jButton1;
    public static javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelannual1;
    private javax.swing.JLabel labele_emr;
    private javax.swing.JLabel labeledate;
    private javax.swing.JLabel labelmed;
    private javax.swing.JTextArea reason;
    private javax.swing.JLabel reasonla;
    private javax.swing.JScrollPane scrolreason;
    private com.toedter.calendar.JDateChooser startdate;
    private javax.swing.JLabel stdatela;
    private javax.swing.JButton sub;
    private javax.swing.JLabel upload;
    // End of variables declaration//GEN-END:variables
}
